name: Publish
on:
  - push
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    strategy:
      matrix:
        python-version:
          - "3.10"
    container:
      image: cimg/python:${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Test
        run: make test
  publish:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    strategy:
      matrix:
        python-version:
          - "3.10"
    if: github.ref == 'refs/heads/main'
    container:
      image: cimg/python:${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Publish package
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: ./scripts/ci-publish.sh jonson
